# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 paths:
  include:
    - 'vulnerability-scan-info/sha256.txt'

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    filePath: 'vulnerability-scan-info/vuln-scan-info.ps1'
  env: 
    SECRET: $(api-secret)

